<template>
  <div ref="echartsMap" style="width: 100%; height: 600px"></div>
</template>

<script>
import map from "@/assets/map/china.json";

export default {
  name: "EchartsMap",
  data() {
    return {
      mapName: "map",
      bangong: [
        //办公
        { name: "陕西", value: 3 },
        { name: "江苏", value: 42 },
        { name: "四川", value: 24 },
        { name: "云南", value: 8 },
        { name: "重庆", value: 6 },
        { name: "湖南", value: 6 },
        { name: "广东", value: 84 },
        { name: "山东", value: 11 },
        { name: "湖北", value: 38 },
        { name: "上海", value: 60 },
        { name: "浙江", value: 24 },
        { name: "江西", value: 5 },
        { name: "安徽", value: 13 },
        { name: "贵州", value: 5 },
        { name: "北京", value: 28 },
        { name: "广西", value: 11 },
        { name: "河南", value: 5 },
        { name: "福建", value: 13 },
        { name: "辽宁", value: 4 },
        { name: "河北", value: 6 },
        { name: "宁夏", value: 1 },
        { name: "山西", value: 1 },
        { name: "吉林", value: 2 },
      ],
      canyin: [
        //餐饮
        { name: "广东", value: 329 },
        { name: "广西", value: 11 },
        { name: "上海", value: 225 },
        { name: "云南", value: 26 },
        { name: "湖北", value: 88 },
        { name: "湖南", value: 37 },
        { name: "福建", value: 20 },
        { name: "河南", value: 12 },
        { name: "江西", value: 12 },
        { name: "山东", value: 17 },
        { name: "河北", value: 7 },
        { name: "安徽", value: 21 },
        { name: "江苏", value: 107 },
        { name: "山西", value: 5 },
        { name: "四川", value: 89 },
        { name: "黑龙江", value: 2 },
        { name: "北京", value: 37 },
        { name: "重庆", value: 24 },
        { name: "浙江", value: 66 },
        { name: "海南", value: 8 },
        { name: "陕西", value: 18 },
        { name: "辽宁", value: 17 },
        { name: "贵州", value: 5 },
        { name: "天津", value: 3 },
        { name: "吉林", value: 4 },
        { name: "宁夏", value: 1 },
        { name: "新疆", value: 3 },
        { name: "青海", value: 1 },
        { name: "甘肃", value: 1 },
        { name: "西藏", value: 3 },
      ],
      fangchan: [
        //房产
        { name: "上海", value: 189 },
        { name: "重庆", value: 52 },
        { name: "四川", value: 74 },
        { name: "江苏", value: 193 },
        { name: "内蒙古", value: 1 },
        { name: "广东", value: 191 },
        { name: "陕西", value: 39 },
        { name: "北京", value: 50 },
        { name: "云南", value: 6 },
        { name: "山东", value: 9 },
        { name: "浙江", value: 39 },
        { name: "河南", value: 9 },
        { name: "辽宁", value: 1 },
        { name: "湖南", value: 11 },
        { name: "河北", value: 3 },
        { name: "湖北", value: 104 },
        { name: "海南", value: 2 },
        { name: "江西", value: 2 },
        { name: "安徽", value: 8 },
        { name: "贵州", value: 4 },
        { name: "黑龙江", value: 6 },
        { name: "福建", value: 6 },
        { name: "吉林", value: 1 },
      ],
      fuzhuang: [
        //服装
        { name: "江苏", value: 104 },
        { name: "湖北", value: 26 },
        { name: "上海", value: 39 },
        { name: "浙江", value: 26 },
        { name: "广东", value: 39 },
        { name: "山东", value: 13 },
        { name: "北京", value: 13 },
      ],
      guanggao: [
        //广告
        { name: "上海", value: 100 },
        { name: "云南", value: 8 },
        { name: "广东", value: 122 },
        { name: "安徽", value: 4 },
        { name: "江苏", value: 20 },
        { name: "北京", value: 33 },
        { name: "浙江", value: 21 },
        { name: "陕西", value: 4 },
        { name: "四川", value: 24 },
        { name: "湖北", value: 23 },
        { name: "河南", value: 5 },
        { name: "", value: 6 },
        { name: "重庆", value: 13 },
        { name: "江西", value: 3 },
        { name: "辽宁", value: 2 },
        { name: "山东", value: 6 },
        { name: "湖南", value: 5 },
        { name: "贵州", value: 1 },
        { name: "福建", value: 3 },
        { name: "吉林", value: 1 },
        { name: "甘肃", value: 1 },
        { name: "新疆", value: 1 },
      ],
      huli: [
        //护理
        { name: "湖北", value: 33 },
        { name: "江苏", value: 46 },
        { name: "安徽", value: 5 },
        { name: "浙江", value: 25 },
        { name: "广东", value: 109 },
        { name: "山东", value: 8 },
        { name: "上海", value: 79 },
        { name: "陕西", value: 7 },
        { name: "四川", value: 38 },
        { name: "云南", value: 12 },
        { name: "甘肃", value: 1 },
        { name: "北京", value: 14 },
        { name: "重庆", value: 9 },
        { name: "河南", value: 4 },
        { name: "江西", value: 3 },
        { name: "辽宁", value: 2 },
        { name: "湖南", value: 2 },
        { name: "广西", value: 1 },
        { name: "黑龙江", value: 1 },
        { name: "河北", value: 1 },
      ],
      jiaju: [
        //家具
        { name: "江苏", value: 25 },
        { name: "安徽", value: 6 },
        { name: "上海", value: 57 },
        { name: "四川", value: 29 },
        { name: "山东", value: 8 },
        { name: "河北", value: 4 },
        { name: "浙江", value: 41 },
        { name: "广东", value: 162 },
        { name: "湖北", value: 20 },
        { name: "江西", value: 5 },
        { name: "云南", value: 9 },
        { name: "贵州", value: 1 },
        { name: "天津", value: 1 },
        { name: "河南", value: 3 },
        { name: "辽宁", value: 4 },
        { name: "重庆", value: 9 },
        { name: "北京", value: 7 },
        { name: "福建", value: 4 },
        { name: "广西", value: 1 },
        { name: "陕西", value: 3 },
        { name: "山西", value: 1 },
      ],
      jiance: [
        //检测
        { name: "广东", value: 113 },
        { name: "安徽", value: 9 },
        { name: "江苏", value: 59 },
        { name: "浙江", value: 37 },
        { name: "河南", value: 8 },
        { name: "云南", value: 6 },
        { name: "上海", value: 59 },
        { name: "北京", value: 15 },
        { name: "宁夏", value: 1 },
        { name: "陕西", value: 6 },
        { name: "新疆", value: 1 },
        { name: "江西", value: 7 },
        { name: "山东", value: 4 },
        { name: "广西", value: 8 },
        { name: "湖北", value: 19 },
        { name: "湖南", value: 9 },
        { name: "河北", value: 7 },
        { name: "福建", value: 11 },
        { name: "重庆", value: 7 },
        { name: "山西", value: 1 },
        { name: "辽宁", value: 3 },
        { name: "内蒙古", value: 2 },
        { name: "四川", value: 3 },
        { name: "贵州", value: 1 },
        { name: "吉林", value: 1 },
        { name: "天津", value: 1 },
        { name: "海南", value: 1 },
        { name: "黑龙江", value: 1 },
      ],
      jianzhu: [
        //建筑
        { name: "广东", value: 86 },
        { name: "江苏", value: 35 },
        { name: "上海", value: 72 },
        { name: "重庆", value: 21 },
        { name: "四川", value: 26 },
        { name: "北京", value: 13 },
        { name: "河南", value: 8 },
        { name: "湖北", value: 24 },
        { name: "浙江", value: 46 },
        { name: "辽宁", value: 5 },
        { name: "云南", value: 12 },
        { name: "山东", value: 6 },
        { name: "湖南", value: 7 },
        { name: "安徽", value: 8 },
        { name: "陕西", value: 9 },
        { name: "黑龙江", value: 1 },
        { name: "贵州", value: 3 },
        { name: "天津", value: 2 },
        { name: "江西", value: 2 },
        { name: "广西", value: 2 },
        { name: "福建", value: 1 },
        { name: "河北", value: 7 },
        { name: "内蒙古", value: 1 },
        { name: "甘肃", value: 2 },
        { name: "海南", value: 1 },
      ],
      jiaoyu: [
        //教育
        { name: "广东", value: 115 },
        { name: "四川", value: 27 },
        { name: "重庆", value: 13 },
        { name: "山东", value: 7 },
        { name: "湖南", value: 8 },
        { name: "福建", value: 3 },
        { name: "山西", value: 1 },
        { name: "湖北", value: 36 },
        { name: "江苏", value: 34 },
        { name: "上海", value: 54 },
        { name: "云南", value: 6 },
        { name: "北京", value: 18 },
        { name: "广西", value: 12 },
        { name: "吉林", value: 5 },
        { name: "江西", value: 7 },
        { name: "安徽", value: 11 },
        { name: "辽宁", value: 2 },
        { name: "陕西", value: 10 },
        { name: "浙江", value: 20 },
        { name: "河南", value: 5 },
        { name: "新疆", value: 1 },
        { name: "贵州", value: 3 },
        { name: "黑龙江", value: 1 },
        { name: "天津", value: 1 },
      ],
      keyan: [
        //科研
        { name: "广西", value: 5 },
        { name: "浙江", value: 106 },
        { name: "江苏", value: 89 },
        { name: "北京", value: 86 },
        { name: "四川", value: 42 },
        { name: "湖北", value: 99 },
        { name: "新疆", value: 7 },
        { name: "陕西", value: 18 },
        { name: "上海", value: 143 },
        { name: "黑龙江", value: 9 },
        { name: "重庆", value: 14 },
        { name: "广东", value: 223 },
        { name: "河南", value: 12 },
        { name: "云南", value: 17 },
        { name: "贵州", value: 4 },
        { name: "江西", value: 11 },
        { name: "山西", value: 18 },
        { name: "湖南", value: 21 },
        { name: "安徽", value: 5 },
        { name: "天津", value: 5 },
        { name: "辽宁", value: 14 },
        { name: "山东", value: 28 },
        { name: "海南", value: 3 },
        { name: "吉林", value: 4 },
        { name: "甘肃", value: 2 },
        { name: "福建", value: 10 },
        { name: "河北", value: 3 },
        { name: "宁夏", value: 1 },
        { name: "青海", value: 1 },
      ],
      lvyou: [
        //旅游
        { name: "上海", value: 70 },
        { name: "四川", value: 56 },
        { name: "广东", value: 76 },
        { name: "重庆", value: 11 },
        { name: "云南", value: 44 },
        { name: "陕西", value: 11 },
        { name: "江苏", value: 24 },
        { name: "湖北", value: 19 },
        { name: "江西", value: 1 },
        { name: "山东", value: 10 },
        { name: "河南", value: 9 },
        { name: "浙江", value: 17 },
        { name: "福建", value: 2 },
        { name: "广西", value: 6 },
        { name: "黑龙江", value: 9 },
        { name: "河北", value: 2 },
        { name: "辽宁", value: 7 },
        { name: "北京", value: 14 },
        { name: "新疆", value: 4 },
        { name: "内蒙古", value: 2 },
        { name: "天津", value: 2 },
        { name: "山西", value: 1 },
        { name: "湖南", value: 1 },
        { name: "安徽", value: 1 },
        { name: "甘肃", value: 1 },
      ],
      qiche: [
        //汽车
        { name: "广东", value: 37 },
        { name: "浙江", value: 11 },
        { name: "湖北", value: 18 },
        { name: "江苏", value: 27 },
        { name: "重庆", value: 13 },
        { name: "四川", value: 21 },
        { name: "上海", value: 16 },
        { name: "甘肃", value: 2 },
        { name: "云南", value: 8 },
        { name: "贵州", value: 1 },
        { name: "江西", value: 7 },
        { name: "陕西", value: 1 },
        { name: "安徽", value: 7 },
        { name: "北京", value: 3 },
        { name: "海南", value: 1 },
        { name: "河北", value: 2 },
        { name: "湖南", value: 1 },
        { name: "内蒙古", value: 1 },
        { name: "山东", value: 1 },
        { name: "河南", value: 2 },
      ],
      ruanjian: [
        //软件
        { name: "江苏", value: 30 },
        { name: "陕西", value: 22 },
        { name: "上海", value: 26 },
        { name: "广东", value: 57 },
        { name: "湖北", value: 10 },
        { name: "安徽", value: 8 },
        { name: "四川", value: 9 },
        { name: "北京", value: 7 },
        { name: "湖南", value: 10 },
        { name: "浙江", value: 9 },
        { name: "辽宁", value: 4 },
        { name: "重庆", value: 3 },
        { name: "福建", value: 1 },
        { name: "江西", value: 1 },
        { name: "天津", value: 1 },
        { name: "山西", value: 1 },
        { name: "山东", value: 1 },
      ],
      xinnengyuan: [
        //新能源
        { name: "广东", value: 130 },
        { name: "江苏", value: 41 },
        { name: "上海", value: 65 },
        { name: "湖北", value: 17 },
        { name: "云南", value: 10 },
        { name: "四川", value: 26 },
        { name: "重庆", value: 10 },
        { name: "甘肃", value: 5 },
        { name: "浙江", value: 16 },
        { name: "安徽", value: 10 },
        { name: "山西", value: 4 },
        { name: "河北", value: 5 },
        { name: "广西", value: 21 },
        { name: "天津", value: 3 },
        { name: "辽宁", value: 3 },
        { name: "山东", value: 3 },
        { name: "海南", value: 1 },
        { name: "北京", value: 16 },
        { name: "湖南", value: 5 },
        { name: "陕西", value: 5 },
        { name: "宁夏", value: 1 },
        { name: "福建", value: 1 },
        { name: "河南", value: 2 },
      ],
      yelian: [
        //冶炼
        { name: "江苏", value: 42 },
        { name: "贵州", value: 29 },
        { name: "江西", value: 55 },
        { name: "上海", value: 19 },
        { name: "广西", value: 12 },
        { name: "湖南", value: 28 },
        { name: "河南", value: 6 },
        { name: "浙江", value: 21 },
        { name: "广东", value: 41 },
        { name: "山东", value: 6 },
        { name: "河北", value: 10 },
        { name: "安徽", value: 23 },
        { name: "辽宁", value: 5 },
        { name: "四川", value: 28 },
        { name: "云南", value: 7 },
        { name: "陕西", value: 14 },
        { name: "湖北", value: 25 },
        { name: "福建", value: 4 },
        { name: "青海", value: 4 },
        { name: "北京", value: 12 },
        { name: "重庆", value: 3 },
        { name: "新疆", value: 2 },
        { name: "黑龙江", value: 1 },
        { name: "宁夏", value: 2 },
        { name: "内蒙古", value: 1 },
      ],
      yingshi: [
        //影视
        { name: "广东", value: 88 },
        { name: "云南", value: 6 },
        { name: "浙江", value: 10 },
        { name: "上海", value: 28 },
        { name: "江苏", value: 9 },
        { name: "山东", value: 12 },
        { name: "辽宁", value: 2 },
        { name: "安徽", value: 1 },
        { name: "北京", value: 11 },
        { name: "湖北", value: 9 },
        { name: "陕西", value: 5 },
        { name: "海南", value: 4 },
        { name: "福建", value: 6 },
        { name: "重庆", value: 2 },
        { name: "湖南", value: 3 },
        { name: "江西", value: 2 },
        { name: "四川", value: 2 },
      ],
      yingjian: [
        //硬件
        { name: "广东", value: 69 },
        { name: "江苏", value: 14 },
        { name: "上海", value: 39 },
        { name: "湖南", value: 12 },
        { name: "湖北", value: 19 },
        { name: "四川", value: 11 },
        { name: "安徽", value: 5 },
        { name: "陕西", value: 8 },
        { name: "浙江", value: 10 },
        { name: "重庆", value: 2 },
        { name: "北京", value: 6 },
        { name: "辽宁", value: 2 },
        { name: "黑龙江", value: 1 },
        { name: "河北", value: 1 },
        { name: "云南", value: 1 },
      ],
      zhengfu: [
        //政府
        { name: "安徽", value: 5 },
        { name: "江苏", value: 40 },
        { name: "河南", value: 7 },
        { name: "广东", value: 113 },
        { name: "浙江", value: 30 },
        { name: "四川", value: 23 },
        { name: "陕西", value: 12 },
        { name: "上海", value: 54 },
        { name: "湖北", value: 39 },
        { name: "北京", value: 18 },
        { name: "山东", value: 3 },
        { name: "海南", value: 2 },
        { name: "湖南", value: 7 },
        { name: "云南", value: 9 },
        { name: "福建", value: 5 },
        { name: "天津", value: 3 },
        { name: "重庆", value: 10 },
        { name: "山西", value: 1 },
        { name: "辽宁", value: 5 },
        { name: "内蒙古", value: 1 },
        { name: "江西", value: 5 },
        { name: "黑龙江", value: 1 },
        { name: "河北", value: 4 },
        { name: "广西", value: 3 },
      ],
      zhongjie: [
        //中介
        { name: "广东", value: 66 },
        { name: "河南", value: 4 },
        { name: "上海", value: 50 },
        { name: "江苏", value: 87 },
        { name: "重庆", value: 24 },
        { name: "四川", value: 33 },
        { name: "湖北", value: 21 },
        { name: "浙江", value: 27 },
        { name: "北京", value: 27 },
        { name: "黑龙江", value: 1 },
        { name: "陕西", value: 11 },
        { name: "海南", value: 2 },
        { name: "湖南", value: 12 },
        { name: "安徽", value: 3 },
        { name: "内蒙古", value: 1 },
        { name: "福建", value: 4 },
        { name: "河北", value: 2 },
        { name: "山东", value: 8 },
        { name: "辽宁", value: 3 },
        { name: "云南", value: 2 },
        { name: "广西", value: 2 },
        { name: "江西", value: 7 },
        { name: "天津", value: 2 },
        { name: "贵州", value: 1 },
      ],
    };
  },
  mounted() {
    this.initMap();
  },
  methods: {
    initMap() {
      // 使用ECharts初始化地图
      const chinaMap = this.$echarts.init(this.$refs.echartsMap);
      //注册地图
      this.$echarts.registerMap("china", map);
      // 地图配置
      var option = {
        tooltip: {
          triggerOn: "click",
          formatter: function (params) {
            return params.name + " : " + params.value;
          },
        },
        // 图例按钮，点击可选择哪些不显示
        legend: {
          orient: "vertical",
          left: "left",
          top: "bottom",
          data: [
            "办公",
            "餐饮",
            "房产",
            "服装",
            "广告",
            "护理",
            "家具",
            "检测",
            "建筑",
            "教育",
            "科研",
            "旅游",
            "汽车",
            "软件",
            "新能源",
            "冶炼",
            "影视",
            "硬件",
            "政府",
            "中介",
          ],
          textStyle: {
            color: "#ff69b4",
          },
        },
        visualMap: {
          min: 0,
          max: 1000,
          left: 26,
          bottom: 40,
          showLabel: !0,
          text: ["高", "低"],
          pieces: [
            {
              gt: 100,
              label: "> 100 人",
              color: "#7f1100",
            },
            {
              gte: 10,
              lte: 100,
              label: "10 - 100 人",
              color: "#ff5428",
            },
            {
              gte: 1,
              lt: 10,
              label: "1 - 9 人",
              color: "#ff8c71",
            },
            {
              gt: 0,
              lt: 1,
              label: "疑似",
              color: "#ffd768",
            },
            {
              value: 0,
              color: "#ffffff",
            },
          ],
          show: !0,
        },
        geo: {
          map: "china",
          roam: !1,
          scaleLimit: {
            min: 1,
            max: 2,
          },
          zoom: 1.23,
          top: 120,
          label: {
            normal: {
              show: !0,
              fontSize: "14",
              color: "rgba(0,0,0,0.7)",
            },
          },
          itemStyle: {
            normal: {
              //shadowBlur: 50,
              //shadowColor: 'rgba(0, 0, 0, 0.2)',
              borderColor: "rgba(0, 0, 0, 0.2)",
            },
            emphasis: {
              areaColor: "#f2d5ad",
              shadowOffsetX: 0,
              shadowOffsetY: 0,
              borderWidth: 0,
            },
          },
        },
        toolbox: {
          show: true,
          feature: {
            saveAsImage: {},
          },
        },
        // 系列列表
        series: [
          {
            name: "办公",
            type: "map",
            geoIndex: 0,
            data:[
        //办公
        { name: "陕西", value: 3 },
        { name: "江苏", value: 42 },
        { name: "四川", value: 24 },
        { name: "云南", value: 8 },
        { name: "重庆", value: 6 },
        { name: "湖南", value: 6 },
        { name: "广东", value: 84 },
        { name: "山东", value: 11 },
        { name: "湖北", value: 38 },
        { name: "上海", value: 60 },
        { name: "浙江", value: 24 },
        { name: "江西", value: 5 },
        { name: "安徽", value: 13 },
        { name: "贵州", value: 5 },
        { name: "北京", value: 28 },
        { name: "广西", value: 11 },
        { name: "河南", value: 5 },
        { name: "福建", value: 13 },
        { name: "辽宁", value: 4 },
        { name: "河北", value: 6 },
        { name: "宁夏", value: 1 },
        { name: "山西", value: 1 },
        { name: "吉林", value: 2 },
      ],
          },
        ],
      };

      // 使用刚指定的配置项和数据显示图表
      chinaMap.setOption(option);
    },
  },
};
</script>

<style>
</style>